INSERT INTO book (title, description, author, isbn, printyear) VALUES ('50 оттенков серого', 'эротический роман британской писательницы Э. Л. Джеймс, написанный и изданный в 2011 году. Роман повествует об истории отношений между предпринимателем Кристианом Греем и выпускницей университета Анастейшей Стил', 'Э. Л. Джеймс', '5-05-000746-0', '2011');
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Братство Кольца', 'Отважный хоббит с друзьями отправляется в полное смертельных опасностей путешествие', 'Дж. Р. Р. Толкина', '5-05-000746-1', 1990);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Две крепости', 'Хоббиты идут в Мордор', 'Дж. Р. Р. Толкина', '5-05-000746-2', 1991);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Возвращение короля', 'Хоббиты пришли в Мордор и уничтожили кольцо. Все счастливы', 'Дж. Р. Р. Толкина', '5-05-000746-3', 1992);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Путешествия Гулливера', 'Тестовое описание книги', 'Джонатан Свифт', '5-05-000746-4', 1993);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Франкенштейн, или Современный Прометей', 'Тестовое описание книги', 'Мэри Шелли', '5-05-000746-5', 1994);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Алиса в стране чудес', 'Тестовое описание книги', 'Льюис Кэрролл', '5-05-000746-6', 1995);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Двадцать тысяч лье под водой', 'Тестовое описание книги', 'Жюль Верн', '5-05-000746-7', 1996);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Странная история доктора Джекила и мистера Хайда', 'История двух противоположных половин единой личности, одновременно — морализаторская притча о двойственности прогресса и ответственности науки перед обществом', 'Роберт Льюис Стивенсон', '5-05-000746-8', 1997);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Янки из Коннектикута при дворе короля Артура', 'Тестовое описание книги', 'Марк Твен', '5-05-000746-9', 1998);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Дракула', 'Тестовое описание книги', 'Брэм Стокер', '5-05-000746-10', 1999);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Война миров', 'Тестовое описание книги', 'Герберт Уэллс', '5-05-000746-11', 2000);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('История будущего', 'Тестовое описание книги', 'Айзек Азимов', '5-05-000746-12', 2001);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Звездный десант', 'Тестовое описание книги', 'Роберт Хайнлайн', '5-05-000746-13', 2002);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Слэн', 'Тестовое описание книги', 'Альфред Элтон Ван-Вогт', '5-05-000746-14', 2003);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Джон Уиндэм', 'Тестовое описание книги', 'День триффидов', '5-05-000746-15', 2004);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Страсти по Лейбовицу', 'Тестовое описание книги', 'Уолтер Миллер', '5-05-000746-16', 2005);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Мальвиль', 'Тестовое описание книги', 'Робер Мерль', '5-05-000746-17', 2006);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Я, робот', 'Тестовое описание книги', 'Айзек Азимов', '5-05-000746-18', 2007);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Мечтают ли андроиды об электроовцах?', 'Тестовое описание книги', 'Филип К. Дик', '5-05-000746-19', 2008);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('Нейромант', 'Тестовое описание книги', 'Уильям Гибсон', '5-05-000746-20', 2009);
INSERT INTO book (title, description, author, isbn, printyear) VALUES ('2001: Космическая Одиссея', 'Тестовое описание книги', 'Артур Кларк', '5-05-000746-21', 2010);
INSERT INTO book (title, description, author, isbn, printyear)
VALUES ('Парк Юрского периода', 'Тестовое описание книги', 'Майкл Крайтон', '5-05-000746-22', 2011);